updated echos

diff --git a/.github/workflows/deploy-to-prod.yml b/.github/workflows/deploy-to-prod.yml
--- a/.github/workflows/deploy-to-prod.yml
+++ b/.github/workflows/deploy-to-prod.yml
@@ -29,59 +29,6 @@ jobs:
     - name: Check that a pull request was made
       shell: bash
       run: |- 
-        # get the pull requests merged into branch deployment-branch-${{ inputs.GIT_TAG }}
-        gh pr list --search "base:deployment-branch-${{ inputs.GIT_TAG }}" --state merged --json number > pr_list.json
-        
-        # get the most recent pull request number 
-        pr_id=$(jq '[.[] | .number][0]' pr_list.json | tr -d \")
-        if [[ "$pr_id" == "" ]]
-        then
-            echo "::error::Could not find a merged pull request for deployment-branch-${{ inputs.GIT_TAG }}"
-            exit 1
-        fi
-        
-        # get the head ref (should be the same commit hash as the given tag)
-        gh pr view $pr_id --json headRefOid > head.json
-        headRefOid=$(jq '.headRefOid' head.json | tr -d \")
-        if [[ "$headRefOid" == "" ]]
-        then
-            echo "::error::Could not get the headRefOid for the pull request #$pr_id"
-            exit 1
-        fi
-
-        # get the base ref (should be the same commit hash as the most recent common ancestor of main & the given tag)
-        gh pr view $pr_id --json baseRefOid > base.json
-        baseRefOid=$(jq '.baseRefOid' base.json | tr -d \")
-        if [[ "$baseRefOid" == "" ]]
-        then
-            echo "::error::Could not get the baseRefOid for the pull request #$pr_id"
-            exit 1
-        fi
-
-        most_recent_ancestor=$(git merge-base main ${{ inputs.GIT_TAG }})
-        if [[ "$baseRefOid" != "$most_recent_ancestor" ]]
-        then
-            echo "::error::Most recent common ancestor of tag ${{ inputs.GIT_TAG }}'s' pull request was not the same as the most recent common ancestor of tag ${{ inputs.GIT_TAG }} and main. baseRefOid: ($baseRefOid) vs most_recent_ancestor: ($most_recent_ancestor)"
-            exit 1
-        fi
-
-        # check that it was reviewed by someone who was not the last committer
-        gh pr view $pr_id --json reviews > reviews.json
-        jq '.reviews | .[] | select(.state=="APPROVED") | .author | .login' reviews.json | tr -d \" > reviewers.txt
-
-        # get the last commiter
-        gh pr view $pr_id --json commits > commits.json
-        last_commit_author=$(jq '.commits | .[0] | .authors | .[0] | .login' commits.json | tr -d \")
-        
-        # reviewer that is not the last commit author
-        reviewer_not_last_commiter=$(cat reviewers.txt | grep -v $last_commit_author)
-        
-        if [[ "$reviewer_not_last_commiter" == "" ]]
-        then
-            echo "::error::Could not find a reviewer that was not the last commit author for pull request #$pr_id"
-            exit 1
-        fi
-
-        # all checks passed if this point is reached
+        echo "::error::foobar" && exit 1
       env:
         GH_TOKEN: ${{ github.token }}
